### ISSUE TITLE
Couple of things on the V40 fork

### ISSUE THREAD

**Issue by uChip** [sparkfun/USB_Weather_Board#4]
Mike, 
I sent you an email about a week ago but I didn't get a response so I don't know if it made it thru.  I noticed an issue with pin numbering on the v40 schematic.  On the 328 pins 13 & 14 are both labeled as Arduino Port D9.  Then in the notes it says that the status LED is on port D11 when the schematic shows that line labeled as D10.

Also, I like the direction of the new version but is there a way I can lobby for a couple of changes?
Thanks,
Chip

**Comment by ToniCorinne** [comment]
Closing this issue out, as the current weather board has been retired. These notes have been copied over to our backend for future revisions of the Weather shield board.
